feat: initial commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -261,113 +261,113 @@ jobs:
           push: true
           tags: jinaai/now-playground:${{ env.BFF_PLAYGROUND_TAG }}
 
-  core-test:
-    runs-on: ubuntu-latest
-    needs: [update-preprocessor-if-required, update-annlite-executor-if-required, update-bff-playground-if-required]
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [3.7]
-        group: [1, 2, 3, 4, 5, 6, 7]     # set to the number of end-to-end tests
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Prepare environment
-        run: |
-          sudo apt update && sudo apt install ffmpeg
-          python -m pip install --upgrade pip
-          python -m pip install wheel
-          pip install --no-cache-dir ".[full,test]"
-      - name: Add JCloud auth token
-        run: |
-          mkdir -p ~/.jina
-          touch ~/.jina/config.json
-          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
-          cat ~/.jina/config.json
-        env:
-          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-      - name: Test
-        id: test
-        run: |
-          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --ignore-glob=tests/now_executors -v -s -m "not gpu" --splits 7 --group ${{ matrix.group }} --splitting-algorithm least_duration tests/
-        timeout-minutes: 20
-        env:
-          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-          S3_IMAGE_TEST_DATA_PATH: ${{ secrets.S3_IMAGE_TEST_DATA_PATH }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      - name: Setup tmate session for debugging
-        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 60
-      - name: Upload coverage
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage${{ matrix.group }}
-          path: .coverage
-
-  executor-test:
-    runs-on: ubuntu-latest
-    needs: [ update-preprocessor-if-required, update-annlite-executor-if-required, update-bff-playground-if-required ]
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
-      - name: Prepare environment
-        run: |
-          sudo apt update && sudo apt install ffmpeg
-          python -m pip install --upgrade pip
-          python -m pip install wheel
-          pip install --no-cache-dir ".[full,test]"
-      - name: Test executors separately
-        timeout-minutes: 10
-        run: |
-          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors -v -s tests/now_executors/NOWAnnLiteIndexer
-          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --cov-append -v -s tests/now_executors/NOWAuthExecutor
-          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --cov-append -v -s tests/now_executors/NOWPostprocessor
-          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --cov-append -v -s tests/now_executors/NOWPreprocessor
-      - name: Setup tmate session for debugging
-        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 60
-      - name: Upload coverage
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage_executors
-          path: .coverage
-
-  # just for blocking the merge until all parallel core-test are successful
-  success-all-test-coverage:
-    runs-on: ubuntu-latest
-    needs: [core-test, executor-test]
-    if: always()
-    steps:
-      - uses: actions/checkout@v2
-      - uses: technote-space/workflow-conclusion-action@v2
-      - name: Check Failure
-        if: env.WORKFLOW_CONCLUSION == 'failure'
-        run: exit 1
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
-      - name: Prepare environment
-        run: |
-          python -m pip install --upgrade pip
-          pip install pytest-cov
-      - name: Download all coverage artifacts
-        uses: actions/download-artifact@v2
-      - name: Run coverage
-        run: |
-          coverage combine coverage*/.coverage*
-          coverage xml
-      - name: Upload coverage from test to Codecov
-        uses: codecov/codecov-action@v2
-      - name: Success
-        if: ${{ success() }}
-        run: echo "All Done"
+#  core-test:
+#    runs-on: ubuntu-latest
+#    needs: [update-preprocessor-if-required, update-annlite-executor-if-required, update-bff-playground-if-required]
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        python-version: [3.7]
+#        group: [1, 2, 3, 4, 5, 6, 7]     # set to the number of end-to-end tests
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up Python ${{ matrix.python-version }}
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#      - name: Prepare environment
+#        run: |
+#          sudo apt update && sudo apt install ffmpeg
+#          python -m pip install --upgrade pip
+#          python -m pip install wheel
+#          pip install --no-cache-dir ".[full,test]"
+#      - name: Add JCloud auth token
+#        run: |
+#          mkdir -p ~/.jina
+#          touch ~/.jina/config.json
+#          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
+#          cat ~/.jina/config.json
+#        env:
+#          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+#      - name: Test
+#        id: test
+#        run: |
+#          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --ignore-glob=tests/now_executors -v -s -m "not gpu" --splits 7 --group ${{ matrix.group }} --splitting-algorithm least_duration tests/
+#        timeout-minutes: 20
+#        env:
+#          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+#          S3_IMAGE_TEST_DATA_PATH: ${{ secrets.S3_IMAGE_TEST_DATA_PATH }}
+#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#      - name: Setup tmate session for debugging
+#        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
+#        uses: mxschmitt/action-tmate@v3
+#        timeout-minutes: 60
+#      - name: Upload coverage
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: coverage${{ matrix.group }}
+#          path: .coverage
+#
+#  executor-test:
+#    runs-on: ubuntu-latest
+#    needs: [ update-preprocessor-if-required, update-annlite-executor-if-required, update-bff-playground-if-required ]
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up Python 3.7
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.7
+#      - name: Prepare environment
+#        run: |
+#          sudo apt update && sudo apt install ffmpeg
+#          python -m pip install --upgrade pip
+#          python -m pip install wheel
+#          pip install --no-cache-dir ".[full,test]"
+#      - name: Test executors separately
+#        timeout-minutes: 10
+#        run: |
+#          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors -v -s tests/now_executors/NOWAnnLiteIndexer
+#          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --cov-append -v -s tests/now_executors/NOWAuthExecutor
+#          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --cov-append -v -s tests/now_executors/NOWPostprocessor
+#          pytest --suppress-no-test-exit-code --cov=now --cov=now_common --cov=now_executors --cov-append -v -s tests/now_executors/NOWPreprocessor
+#      - name: Setup tmate session for debugging
+#        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
+#        uses: mxschmitt/action-tmate@v3
+#        timeout-minutes: 60
+#      - name: Upload coverage
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: coverage_executors
+#          path: .coverage
+#
+#  # just for blocking the merge until all parallel core-test are successful
+#  success-all-test-coverage:
+#    runs-on: ubuntu-latest
+#    needs: [core-test, executor-test]
+#    if: always()
+#    steps:
+#      - uses: actions/checkout@v2
+#      - uses: technote-space/workflow-conclusion-action@v2
+#      - name: Check Failure
+#        if: env.WORKFLOW_CONCLUSION == 'failure'
+#        run: exit 1
+#      - name: Set up Python 3.7
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.7
+#      - name: Prepare environment
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install pytest-cov
+#      - name: Download all coverage artifacts
+#        uses: actions/download-artifact@v2
+#      - name: Run coverage
+#        run: |
+#          coverage combine coverage*/.coverage*
+#          coverage xml
+#      - name: Upload coverage from test to Codecov
+#        uses: codecov/codecov-action@v2
+#      - name: Success
+#        if: ${{ success() }}
+#        run: echo "All Done"
