chore: debug CI output

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -125,16 +125,25 @@ jobs:
         test-path: ${{fromJson(needs.prep-testbed.outputs.matrix)}}
     steps:
       - uses: actions/checkout@v2
+      - name: Print author name with an environment variable
+        run: |
+          echo ${{ failure() }}
+          echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
+          echo ${{ failure() }} || (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
+#      - name: Setup tmate session for debugging
+#        if: ${{ failure() }} || (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
+#        uses: mxschmitt/action-tmate@v3
+#        timeout-minutes: 30
       - name: Set up Python ${{ matrix.python-version }}
         uses: actions/setup-python@v2
         with:
           python-version: ${{ matrix.python-version }}
-      - name: Prepare enviroment
-        run: |
-          sudo apt update && sudo apt install ffmpeg
-          python -m pip install --upgrade pip
-          python -m pip install wheel
-          pip install --no-cache-dir ".[full,test]"
+#      - name: Prepare enviroment
+#        run: |
+#          sudo apt update && sudo apt install ffmpeg
+#          python -m pip install --upgrade pip
+#          python -m pip install wheel
+#          pip install --no-cache-dir ".[full,test]"
       - name: Add JCloud auth token
         run: |
           mkdir -p ~/.jina
@@ -143,32 +152,31 @@ jobs:
           echo ~/.jina/config.json
         env:
           WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-      - name: Test
-        id: test
+      - name: Print author name with an environment variable
         run: |
-          pytest --suppress-no-test-exit-code --cov=now --cov-report=xml \
-            -v -s -m "not gpu" ${{ matrix.test-path }}
-          echo "::set-output name=codecov_flag::now"
-        timeout-minutes: 25
-      - name: Check codecov file
-        id: check_files
-        uses: andstor/file-existence-action@v1
-        with:
-          files: "coverage.xml"
-      - name: Upload coverage from test to Codecov
-        uses: codecov/codecov-action@v2
-        if: steps.check_files.outputs.files_exists == 'true' && ${{ matrix.python-version }} == '3.7'
-        with:
-          file: coverage.xml
-          flags: ${{ steps.test.outputs.codecov_flag }}
-          fail_ci_if_error: false
+          echo ${{ failure() }}
+          echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
+          echo ${{ failure() }} || (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
+#      - name: Test
+#        id: test
+#        run: |
+#          pytest --suppress-no-test-exit-code --cov=now --cov-report=xml \
+#            -v -s -m "not gpu" ${{ matrix.test-path }}
+#          echo "::set-output name=codecov_flag::now"
+#        timeout-minutes: 25
+#      - name: Check codecov file
+#        id: check_files
+#        uses: andstor/file-existence-action@v1
+#        with:
+#          files: "coverage.xml"
+#      - name: Upload coverage from test to Codecov
+#        uses: codecov/codecov-action@v2
+#        if: steps.check_files.outputs.files_exists == 'true' && ${{ matrix.python-version }} == '3.7'
+#        with:
+#          file: coverage.xml
+#          flags: ${{ steps.test.outputs.codecov_flag }}
+#          fail_ci_if_error: false
 #          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
-      - name: Setup tmate session for debugging
-        if: |
-          ${{ failure() }} ||
-          (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 30
 
   # just for blocking the merge until all parallel core-test are successful
   success-all-test:
