feat: skip ci

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,7 +4,7 @@ on:
   workflow_dispatch:
     inputs:
       debug_enabled:
-        description: 'Run the tests with tmate debugging enabled'
+        description: "Run the tests with tmate debugging enabled"
         required: false
         default: false
 
@@ -341,57 +341,64 @@ jobs:
           NOW_AUTOCOMPLETE_VERSION: ${{ env.NOW_AUTOCOMPLETE_VERSION }}
         run: JINA_AUTH_TOKEN=${{ secrets.NOW_STAGING_FLORIAN }} jina hub push --verbose --force-update NOWAutoCompleteExecutor2 now/executor/autocomplete/. -t latest --protected-tag $NOW_AUTOCOMPLETE_VERSION --build-env JINA_NOW_COMMIT_SHA=${{ github.event.pull_request.head.sha }}
 
-  core-test:
-    runs-on: ubuntu-latest
-    needs: [ update-preprocessor-if-required, update-bff-playground-if-required,  update-autocomplete-executor-if-required, update-qdrant-executor-if-required, update-elastic-executor-if-required]
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [3.7]
-        group: [1, 2, 3, 4, 5, 6, 7, 8, 9]     # set to the number of end-to-end tests + 1
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Prepare environment
-        run: |
-          sudo apt update && sudo apt install ffmpeg
-          python -m pip install --upgrade pip
-          python -m pip install wheel
-          pip install --no-cache-dir ".[full,test]"
-      - name: Add JCloud auth token
-        run: |
-          mkdir -p ~/.jina
-          touch ~/.jina/config.json
-          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
-          cat ~/.jina/config.json
-        env:
-          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-      - name: Test
-        id: test
-        run: |
-          pytest --suppress-no-test-exit-code --cov=now --ignore-glob=tests/executor -v -s -m "not gpu" --splits 9 --group ${{ matrix.group }} --splitting-algorithm least_duration tests/
-        timeout-minutes: 25
-        env:
-          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-          S3_IMAGE_TEST_DATA_PATH: ${{ secrets.S3_IMAGE_TEST_DATA_PATH }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      - name: Setup tmate session for debugging
-        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 60
-      - name: Upload coverage
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage${{ matrix.group }}
-          path: .coverage
+  # core-test:
+  #   runs-on: ubuntu-latest
+  #   needs: [ update-preprocessor-if-required, update-bff-playground-if-required,  update-autocomplete-executor-if-required, update-qdrant-executor-if-required, update-elastic-executor-if-required]
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: [3.7]
+  #       group: [1, 2, 3, 4, 5, 6, 7, 8, 9]     # set to the number of end-to-end tests + 1
+  #   steps:
+  #     - uses: actions/checkout@v2
+  #     - name: Set up Python ${{ matrix.python-version }}
+  #       uses: actions/setup-python@v2
+  #       with:
+  #         python-version: ${{ matrix.python-version }}
+  #     - name: Prepare environment
+  #       run: |
+  #         sudo apt update && sudo apt install ffmpeg
+  #         python -m pip install --upgrade pip
+  #         python -m pip install wheel
+  #         pip install --no-cache-dir ".[full,test]"
+  #     - name: Add JCloud auth token
+  #       run: |
+  #         mkdir -p ~/.jina
+  #         touch ~/.jina/config.json
+  #         echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
+  #         cat ~/.jina/config.json
+  #       env:
+  #         WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+  #     - name: Test
+  #       id: test
+  #       run: |
+  #         pytest --suppress-no-test-exit-code --cov=now --ignore-glob=tests/executor -v -s -m "not gpu" --splits 9 --group ${{ matrix.group }} --splitting-algorithm least_duration tests/
+  #       timeout-minutes: 25
+  #       env:
+  #         WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+  #         S3_IMAGE_TEST_DATA_PATH: ${{ secrets.S3_IMAGE_TEST_DATA_PATH }}
+  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+  #     - name: Setup tmate session for debugging
+  #       if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
+  #       uses: mxschmitt/action-tmate@v3
+  #       timeout-minutes: 60
+  #     - name: Upload coverage
+  #       uses: actions/upload-artifact@v2
+  #       with:
+  #         name: coverage${{ matrix.group }}
+  #         path: .coverage
 
   executor-test:
     runs-on: ubuntu-latest
-    needs: [ update-preprocessor-if-required, update-qdrant-executor-if-required, update-bff-playground-if-required, update-elastic-executor-if-required, update-autocomplete-executor-if-required]
+    needs:
+      [
+        update-preprocessor-if-required,
+        update-qdrant-executor-if-required,
+        update-bff-playground-if-required,
+        update-elastic-executor-if-required,
+        update-autocomplete-executor-if-required,
+      ]
     steps:
       - uses: actions/checkout@v2
       - name: Set up Python 3.7
