fix: reproduce attempt

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -155,6 +155,67 @@ jobs:
           executor_id: 2m00g87k
           jina_auth_token: ${{ secrets.WOLF_TOKEN }}
 
+  local-tests:
+    runs-on: ubuntu-latest
+    needs:
+      [
+        update-preprocessor,
+        update-elastic,
+        update-autocomplete,
+        update-gateway,
+      ]
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set AWS profile
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: eu-west-1
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v2
+        with:
+          python-version: [3.7]
+      - name: Prepare environment
+        run: |
+          python -m pip install --upgrade pip
+          python -m pip install wheel
+          pip install --no-cache-dir ".[full,test]"
+      - name: Add JCloud auth token
+        run: |
+          mkdir -p ~/.jina
+          touch ~/.jina/config.json
+          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
+          cat ~/.jina/config.json
+        env:
+          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+      - name: Test
+        id: test
+        run: |
+          pytest --suppress-no-test-exit-code --cov=now --cov-report=xml -v -s -m "not gpu" tests/integration/local
+          echo "codecov_flag=now" >> $GITHUB_OUTPUT
+
+        timeout-minutes: 20
+        env:
+          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+          S3_SCHEMA_FOLDER_PATH: ${{ secrets.S3_SCHEMA_FOLDER_PATH }}
+      #      - name: Setup tmate session for debugging
+      #        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
+      #        uses: mxschmitt/action-tmate@v3
+      #        timeout-minutes: 60
+      - name: Check codecov file
+        id: check_files
+        uses: andstor/file-existence-action@v1
+        with:
+          files: "coverage.xml"
+      - name: Upload coverage from test to Codecov
+        uses: codecov/codecov-action@v2
+        if: steps.check_files.outputs.files_exists == 'true'
+        with:
+          file: coverage.xml
+          name: ${{ matrix.group }}-codecov
+          flags: ${{ steps.test.outputs.codecov_flag }}
+          fail_ci_if_error: false
   core-test:
     runs-on: ubuntu-latest
     needs:
