fix: trial

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -126,7 +126,7 @@ jobs:
     steps:
       - uses: actions/checkout@v2
       - name: Print author name with an environment variable
-        run: echo ${{ failure() }} || (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
+        run: echo ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}
 #      - name: Setup tmate session for debugging
 #        if: ${{ failure() }} || (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
 #        uses: mxschmitt/action-tmate@v3
@@ -149,8 +149,8 @@ jobs:
           echo ~/.jina/config.json
         env:
           WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-      - name: Print author name with an environment variable
-        run: echo ${{ failure() }} || (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
+#      - name: Print author name with an environment variable
+#        run: echo ${{ failure() }} || (${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }})
 #      - name: Test
 #        id: test
 #        run: |
