fix: commit

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -53,57 +53,57 @@ jobs:
 #            This message will be deleted automatically when the commit messages get fixed.
 #          reaction-type: "eyes"
 
-#  lint-flake-8:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#      - name: Set up Python 3.7
-#        uses: actions/setup-python@v2
-#        with:
-#          python-version: 3.7
-#      - name: Lint with flake8
-#        run: |
-#          pip install flake8
-#          # stop the build if there are Python syntax errors or undefined names
-#          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist,tests/,jina/resources/,now/thirdparty
-#          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
-#          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist,tests/,jina/resources/,now/thirdparty
-#
-#  check-black:
-#    runs-on: ubuntu-latest
-#    steps:
-#      - uses: actions/checkout@v2
-#        with:
-#          fetch-depth: 0
-#      - name: Set up Python 3.7
-#        uses: actions/setup-python@v2
-#        with:
-#          python-version: 3.7
-#      - id: file_changes
-#        uses: Ana06/get-changed-files@v1.2
-#      - name: check black
-#        run: ./scripts/black.sh
-#        env:
-#          CHANGED_FILES: ${{ steps.file_changes.outputs.added_modified }}
-#
-#  update-preprocessor:
-#    runs-on: ubuntu-latest
+  lint-flake-8:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.7
+      - name: Lint with flake8
+        run: |
+          pip install flake8
+          # stop the build if there are Python syntax errors or undefined names
+          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist,tests/,jina/resources/,now/thirdparty
+          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
+          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .git,__pycache__,docs/source/conf.py,old,build,dist,tests/,jina/resources/,now/thirdparty
+
+  check-black:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+        with:
+          fetch-depth: 0
+      - name: Set up Python 3.7
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.7
+      - id: file_changes
+        uses: Ana06/get-changed-files@v1.2
+      - name: check black
+        run: ./scripts/black.sh
+        env:
+          CHANGED_FILES: ${{ steps.file_changes.outputs.added_modified }}
+
+  update-preprocessor:
+    runs-on: ubuntu-latest
 #    needs: [lint-flake-8, check-black]
-#    steps:
-#      - uses: actions/checkout@v2
-#      - uses: ./.github/actions/push-executor
-#        with:
-#          executor_version_name: NOW_PREPROCESSOR_VERSION
-#          executor_name: NOWPreprocessor
-#          executor_path: now/executor/preprocessor
-#          # for some reason, the first filter condition needs a different indentation
-#          has_changed_filter: |
-#            - now/app/base/**
-#              - now/common/preprocess.py
-#              - now/executor/preprocessor/**
-#              - now/executor/abstract/auth/**
-#          executor_id: vlxgoxlv
-#          jina_auth_token: ${{ secrets.NOW_PREPROCESSOR_JCLOUD_TOKEN }}
+    steps:
+      - uses: actions/checkout@v2
+      - uses: ./.github/actions/push-executor
+        with:
+          executor_version_name: NOW_PREPROCESSOR_VERSION
+          executor_name: NOWPreprocessor
+          executor_path: now/executor/preprocessor
+          # for some reason, the first filter condition needs a different indentation
+          has_changed_filter: |
+            - now/app/base/**
+              - now/common/preprocess.py
+              - now/executor/preprocessor/**
+              - now/executor/abstract/auth/**
+          executor_id: vlxgoxlv
+          jina_auth_token: ${{ secrets.NOW_PREPROCESSOR_JCLOUD_TOKEN }}
 #
 #  update-qdrant:
 #    runs-on: ubuntu-latest
@@ -220,114 +220,117 @@ jobs:
 #          context: deployment/playground/.
 #          push: true
 #          tags: jinaai/now-playground:${{ env.BFF_PLAYGROUND_TAG }}
-  core-test:
-    runs-on: ubuntu-latest
-#    needs: [ update-preprocessor, update-bff-playground,  update-autocomplete-executor, update-qdrant-executor, update-elastic-executor]
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: [3.7]
-        group: [1, 2, 3, 4, 5, 6, 7, 8, 9]     # set to the number of end-to-end tests + 1
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python ${{ matrix.python-version }}
-        uses: actions/setup-python@v2
-        with:
-          python-version: ${{ matrix.python-version }}
-      - name: Prepare environment
-        run: |
-          sudo apt update && sudo apt install ffmpeg
-          python -m pip install --upgrade pip
-          python -m pip install wheel
-          pip install --no-cache-dir ".[full,test]"
-      - name: Add JCloud auth token
-        run: |
-          mkdir -p ~/.jina
-          touch ~/.jina/config.json
-          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
-          cat ~/.jina/config.json
-        env:
-          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-      - name: Test
-        id: test
-        run: |
-          pytest --suppress-no-test-exit-code --cov=now --ignore-glob=tests/executor -v -s -m "not gpu" --splits 9 --group ${{ matrix.group }} --splitting-algorithm least_duration tests/
-        timeout-minutes: 25
-        env:
-          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
-          S3_IMAGE_TEST_DATA_PATH: ${{ secrets.S3_IMAGE_TEST_DATA_PATH }}
-          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-      - name: Setup tmate session for debugging
-        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 60
-      - name: Upload coverage
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage${{ matrix.group }}
-          path: .coverage
 
-  executor-test:
-    runs-on: ubuntu-latest
-#    needs: [ update-preprocessor-if-required, update-qdrant-executor-if-required, update-bff-playground-if-required, update-elastic-executor-if-required, update-autocomplete-executor-if-required]
-    steps:
-      - uses: actions/checkout@v2
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
-      - name: Prepare environment
-        run: |
-          sudo apt update && sudo apt install ffmpeg
-          python -m pip install --upgrade pip
-          python -m pip install wheel
-          pip install --no-cache-dir ".[full,test]"
-      - name: Test executors separately
-        timeout-minutes: 10
-        run: |
-          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/auth
-          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/indexer/base
-          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/indexer/elastic
-          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/preprocessor
-          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/autocomplete
-      - name: Setup tmate session for debugging
-        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
-        uses: mxschmitt/action-tmate@v3
-        timeout-minutes: 60
-      - name: Upload coverage
-        uses: actions/upload-artifact@v2
-        with:
-          name: coverage_executor
-          path: .coverage
 
-  # just for blocking the merge until all parallel core-test are successful
-  success-all-test-coverage:
-    runs-on: ubuntu-latest
-    needs: [core-test, executor-test]
-    if: always()
-    steps:
-      - uses: actions/checkout@v2
-      - uses: technote-space/workflow-conclusion-action@v2
-      - name: Check Failure
-        if: env.WORKFLOW_CONCLUSION == 'failure'
-        run: exit 1
-      - name: Set up Python 3.7
-        uses: actions/setup-python@v2
-        with:
-          python-version: 3.7
-      - name: Prepare environment
-        run: |
-          python -m pip install --upgrade pip
-          pip install pytest-cov
-      - name: Download all coverage artifacts
-        uses: actions/download-artifact@v2
-      - name: Run coverage
-        run: |
-          coverage combine coverage*/.coverage*
-          coverage xml
-      - name: Upload coverage from test to Codecov
-        uses: codecov/codecov-action@v2
-      - name: Success
-        if: ${{ success() }}
-        run: echo "All Done"
+
+#  core-test:
+#    runs-on: ubuntu-latest
+##    needs: [ update-preprocessor, update-bff-playground,  update-autocomplete-executor, update-qdrant-executor, update-elastic-executor]
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        python-version: [3.7]
+#        group: [1, 2, 3, 4, 5, 6, 7, 8, 9]     # set to the number of end-to-end tests + 1
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up Python ${{ matrix.python-version }}
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: ${{ matrix.python-version }}
+#      - name: Prepare environment
+#        run: |
+#          sudo apt update && sudo apt install ffmpeg
+#          python -m pip install --upgrade pip
+#          python -m pip install wheel
+#          pip install --no-cache-dir ".[full,test]"
+#      - name: Add JCloud auth token
+#        run: |
+#          mkdir -p ~/.jina
+#          touch ~/.jina/config.json
+#          echo "{\"auth_token\": \"${WOLF_TOKEN}\"}" > ~/.jina/config.json
+#          cat ~/.jina/config.json
+#        env:
+#          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+#      - name: Test
+#        id: test
+#        run: |
+#          pytest --suppress-no-test-exit-code --cov=now --ignore-glob=tests/executor -v -s -m "not gpu" --splits 9 --group ${{ matrix.group }} --splitting-algorithm least_duration tests/
+#        timeout-minutes: 25
+#        env:
+#          WOLF_TOKEN: ${{ secrets.WOLF_TOKEN }}
+#          S3_IMAGE_TEST_DATA_PATH: ${{ secrets.S3_IMAGE_TEST_DATA_PATH }}
+#          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+#          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+#      - name: Setup tmate session for debugging
+#        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
+#        uses: mxschmitt/action-tmate@v3
+#        timeout-minutes: 60
+#      - name: Upload coverage
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: coverage${{ matrix.group }}
+#          path: .coverage
+#
+#  executor-test:
+#    runs-on: ubuntu-latest
+##    needs: [ update-preprocessor-if-required, update-qdrant-executor-if-required, update-bff-playground-if-required, update-elastic-executor-if-required, update-autocomplete-executor-if-required]
+#    steps:
+#      - uses: actions/checkout@v2
+#      - name: Set up Python 3.7
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.7
+#      - name: Prepare environment
+#        run: |
+#          sudo apt update && sudo apt install ffmpeg
+#          python -m pip install --upgrade pip
+#          python -m pip install wheel
+#          pip install --no-cache-dir ".[full,test]"
+#      - name: Test executors separately
+#        timeout-minutes: 10
+#        run: |
+#          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/auth
+#          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/indexer/base
+#          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/indexer/elastic
+#          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/preprocessor
+#          pytest --suppress-no-test-exit-code --cov=now --cov-append -v -s tests/executor/autocomplete
+#      - name: Setup tmate session for debugging
+#        if: ${{ failure() || (github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled) }}
+#        uses: mxschmitt/action-tmate@v3
+#        timeout-minutes: 60
+#      - name: Upload coverage
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: coverage_executor
+#          path: .coverage
+#
+#  # just for blocking the merge until all parallel core-test are successful
+#  success-all-test-coverage:
+#    runs-on: ubuntu-latest
+#    needs: [core-test, executor-test]
+#    if: always()
+#    steps:
+#      - uses: actions/checkout@v2
+#      - uses: technote-space/workflow-conclusion-action@v2
+#      - name: Check Failure
+#        if: env.WORKFLOW_CONCLUSION == 'failure'
+#        run: exit 1
+#      - name: Set up Python 3.7
+#        uses: actions/setup-python@v2
+#        with:
+#          python-version: 3.7
+#      - name: Prepare environment
+#        run: |
+#          python -m pip install --upgrade pip
+#          pip install pytest-cov
+#      - name: Download all coverage artifacts
+#        uses: actions/download-artifact@v2
+#      - name: Run coverage
+#        run: |
+#          coverage combine coverage*/.coverage*
+#          coverage xml
+#      - name: Upload coverage from test to Codecov
+#        uses: codecov/codecov-action@v2
+#      - name: Success
+#        if: ${{ success() }}
+#        run: echo "All Done"
